---
repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
    #
    # Go Mod Tidy
    #
      - id: go-mod-tidy
      - id: go-mod-tidy-repo
    #
    # Formatters
    #
      - id: go-fmt
      - id: go-fmt-repo
